Warn if file fails to unpack

diff --git a/public/install b/public/install
--- a/public/install
+++ b/public/install
@@ -44,4 +44,11 @@ if [ $? != 0 ]; then
   exit 1
 fi
 
-tar zxvf $FILE && mv exercism /usr/local/bin
+tar zxvf $FILE
+
+if [ $? != 0 ]; then
+  echo "Failed to unpack $FILE"
+  exit 1
+fi
+
+mv exercism /usr/local/bin
